### PR TITLE
gpbackman: env-var fallback for --history-db and fail loud when DB is missing

### LINKED ISSUE #96: [Bug] gpbackman: --history-db should fall back to $COORDINATOR_DATA_DIRECTORY, and OpenHistoryDB should not silently create empty files
### Apache Cloudberry and cloudberry-backup version

cloudberry  2.0.x & 2.1.x
cloudberry-backup main                                                                                                                                                                            

### What happened

### Summary                                               
                                                                                                                                                                             
  `gpbackman` makes two reasonable defaults harder than they need to be:                                                                                                     
                                                                                                                                                                             
  1. The `--history-db` flag has no fallback to the standard                                                                                                                 
     `$COORDINATOR_DATA_DIRECTORY` / `$MASTER_DATA_DIRECTORY` env vars
     that the Cloudberry/Greenplum environment scripts already set.                                                                                                          
  2. When the resolved path does not exist, SQLite silently creates an
     empty database, and the next query fails with the misleading                                                                                                            
     `no such table: backups`. An empty `gpbackup_history.db` is also                                                                                                        
     left behind in `cwd`, polluting unrelated working directories.                                                                                                          
                                                                                                                                                                             
  ### Reproduce on `main`                                                                                                                                                    
                                                                                                                                                                             
  ```console                                                                                                                                                                 
  $ which gpbackman                                         
  /usr/local/cloudberry/bin/gpbackman

  $ cd /tmp                       # any directory without a history DB
  $ gpbackman backup-info                                                                                                                                                    
  [ERROR]:-Unable to read data from history db. Error: no such table: backups
                                                                                                                                                                             
  $ ls /tmp/gpbackup_history.db                             
  -rw-r--r-- 1 gpadmin gpadmin 0 Apr 29 12:40 /tmp/gpbackup_history.db                                                                                                       
                                ^^^ silently created, polluting cwd                                                                                                          
                                                                                                                                                                             
  Expected behaviour                                                                                                                                                         
                                                                                                                                                                             
  - When --history-db is omitted, gpbackman should look up                                                                                                                   
  $COORDINATOR_DATA_DIRECTORY/gpbackup_history.db (and then
  $MASTER_DATA_DIRECTORY/gpbackup_history.db for older installs)                                                                                                             
  before falling back to cwd. This matches how operators already                                                                                                             
  source the cluster environment.                                                                                                                                            
  - When the resolved file does not exist, gpbackman should fail loud                                                                                                        
  with a clear, actionable error and not create an empty SQLite                                                                                                              
  database on disk.                                                                                                                                                          
                                                            
  Why this matters                                                                                                                                                           
                                                            
  - Operators routinely run gpbackman from ~ after sourcing                                                                                                                  
  greenplum_path.sh / equivalent. Today they must always type the
  full coordinator path, which is fragile across cluster layouts.                                                                                                            
  - The "silent create + cryptic later error" UX has bitten me during                                                                                                        
  exploration; the failure mode is non-local and easy to misdiagnose                                                                                                         
  as a corrupt history database.                                                                                                                                             
                                                                                                                                                                             
 

### What you think should happen instead

 Proposed approach                                                                                                                                                          
                                                                                                                                                                             
  - Resolve --history-db empty → $COORDINATOR_DATA_DIRECTORY →                                                                                                               
  $MASTER_DATA_DIRECTORY → bare filename in cwd (last resort,
  preserves existing behaviour).                                                                                                                                             
  - In OpenHistoryDB, pre-check with os.Stat and open SQLite via the
  file:<path>?mode=rw URI (read+write but never create).                                                                                                                     
  - Friendly error message that names the missing path and points at the
  flag and env vars.                                                                                                                                                         
                                                                                                                                                                             


### Operating System

rockylinux 9.x / RHEL 9.X

### PR DESCRIPTION
**Pull request by talmacschen-arch**
Fixes #96

## Motivation

When `gpbackman backup-info` (or any other gpbackman subcommand) is run
without `--history-db`, the current code drops down to a relative
`gpbackup_history.db` resolved against the current directory. Two
problems follow:

1. The cluster's real history DB lives under
   `$COORDINATOR_DATA_DIRECTORY/gpbackup_history.db` (or the legacy
   `$MASTER_DATA_DIRECTORY` on older installs), which is rarely the
   user's shell `cwd`. Operators end up typing the long path on every
   invocation despite the relevant env vars already being set by the
   standard cluster environment scripts.

2. SQLite's default open mode silently **creates** a new empty database
   when the file is missing. The very next query then fails with
   `no such table: backups`, which is confusing and leaves an empty
   `gpbackup_history.db` litter in `cwd`.

Reproducer (current behaviour on `main`):

```console
$ cd /tmp/empty
$ gpbackman backup-info
[ERROR]:-Unable to read data from history db. Error: no such table: backups
$ ls
gpbackup_history.db   # ← silently created, 0 rows, polluted cwd
```

## Changes

* **`gpbackman/cmd/wrappers.go`** — `getHistoryDBPath` resolves the path
  in order: `--history-db` → `$COORDINATOR_DATA_DIRECTORY` →
  `$MASTER_DATA_DIRECTORY` → bare filename in `cwd` (preserved for
  backward compatibility).
* **`gpbackman/gpbckpconfig/utils_db.go`** — `OpenHistoryDB` now
  pre-checks the file with `os.Stat` and opens SQLite via the
  `file:<path>?mode=rw` URI. Missing files surface a clear error that
  references `--history-db` and the env vars; no empty file is ever
  created.
* **Help text** updated for the `--history-db` flag and every
  command's `Long` description; `gpbackman/COMMANDS.md` and
  `gpbackman/README.md` aligned.
* **Tests** added/extended in `wrappers_test.go` (env-var resolution
  order, explicit-wins-over-env) and in `utils_db_test.go` (friendly
  error + no-file-created regression, happy-path open).

## Backward compatibility

Fully compatible. The old "search the current directory" behaviour is
preserved as the last fallback, so any existing scripts that rely on
running gpbackman from a directory containing `gpbackup_history.db`
continue to work unchanged. Users who currently pass `--history-db`
explicitly are unaffected.

The only user-visible *behaviour* change is that running gpbackman
against a non-existent path now errors immediately with a clear message
instead of producing a misleading "no such table: backups" error after
silently creating an empty file. This is the intended fix.

## How tested

* `go test ./gpbackman/cmd/... ./gpbackman/gpbckpconfig/... ./gpbackman/textmsg/...` — all pass.
* `make build` — five binaries built cleanly.
* Manual smoke test against a real cluster history DB:
  * Empty `cwd`, no env → friendly error, no file created. ✅
  * `COORDINATOR_DATA_DIRECTORY` pointing at a non-existent path → friendly error mentioning the resolved path. ✅
  * `COORDINATOR_DATA_DIRECTORY` pointing at the coordinator data dir → backup list rendered without `--history-db`. ✅

## Notes

* DCO `Signed-off-by` included on both commits.
* See #96 for additional discussion / open questions (env-var name choice, optional `GPBACKMAN_HISTORY_DB` override).

### CODE REVIEW

File: gpbackman/cmd/wrappers.go [hunk 1]
```diff
@@ -81,12 +81,24 @@ func setLogLevelFile(level string) error {
 	return nil
 }
 
+// getHistoryDBPath resolves the path to the gpbackup_history.db file.
+// When the --history-db flag is empty, fall back (in order) to the
+// COORDINATOR_DATA_DIRECTORY and MASTER_DATA_DIRECTORY environment variables
+// that the standard Cloudberry/Greenplum environment scripts export, so that
```
Comment (MisterRaindrop) [inline gpbackman/cmd/wrappers.go]: `Cloudberry/Greenplum environment` remove Greenplum is better

File: gpbackman/README.md [hunk 2]
```diff
@@ -53,7 +53,7 @@ Available Commands:
 
 Flags:
   -h, --help                       help for gpbackman
-      --history-db string          full path to the gpbackup_history.db file
+      --history-db string          full path to the gpbackup_history.db file (if unset, falls back to $COORDINATOR_DATA_DIRECTORY/gpbackup_history.db, then $MASTER_DATA_DIRECTORY/gpbackup_history.db, then the current directory)
```
Comment (MisterRaindrop) [inline gpbackman/README.md]: Suggest making it more concise

File: gpbackman/gpbckpconfig/utils_db.go [hunk 3]
```diff
@@ -21,15 +21,38 @@ package gpbckpconfig
...
+					"COORDINATOR_DATA_DIRECTORY (or MASTER_DATA_DIRECTORY), "+
+					"or run gpbackman from the directory that contains "+
+					"gpbackup_history.db",
+				historyDBPath,
+			)
+		}
+		return nil, err
+	}
+	// mode=rw opens an existing database for read+write but never creates one.
+	db, err := sql.Open("sqlite3", "file:"+historyDBPath+"?mode=rw")
```
Comment (MisterRaindrop) [inline gpbackman/gpbckpconfig/utils_db.go:55]: `db, err := sql.Open("sqlite3", historyDBPath)`
The original code didn’t grant read and write permissions.
Isn’t the permission granted here excessively broad?

File: gpbackman/cmd/wrappers.go [hunk 4]
```diff
@@ -81,12 +81,24 @@ func setLogLevelFile(level string) error {
...
+// the path on every invocation. As a last resort, return the bare filename
+// (resolved against the current working directory), preserving the previous
+// behaviour.
 func getHistoryDBPath(historyDBPath string) string {
-	var historyDBName = historyDBNameConst
 	if historyDBPath != "" {
 		return historyDBPath
 	}
-	return historyDBName
+	for _, envVar := range historyDBEnvVars {
```
Comment (MisterRaindrop) [inline gpbackman/cmd/wrappers.go]: Concern: when CWD, $COORDINATOR_DATA_DIRECTORY and $MASTER_DATA_DIRECTORY
  all contain a gpbackup_history.db (common on a jump host managing
  multiple clusters, or when a stale gpadmin profile is sourced), an
  ordered-priority lookup becomes an implicit convention users have to
  learn from docs. For destructive commands (backup-delete, history-clean)
  that's a real footgun — the user thinks they're operating on cluster A
  and silently hits cluster B's history DB.

  We already have `--history-db` for the explicit case. If auto-discovery
  is desired, I'd rather see it behind an opt-in flag (e.g.
  `--auto-load-history-db` or `--from-coordinator-data-dir`) so the two
  behaviors are clearly separated, and the default stays explicit.

File: gpbackman/README.md (hunk 2 above)
Comment (talmacschen-arch) [reply gpbackman/README.md]: OK

File: gpbackman/cmd/wrappers.go (hunk 1 above)
Comment (talmacschen-arch) [reply gpbackman/cmd/wrappers.go]: OK

File: gpbackman/gpbckpconfig/utils_db.go (hunk 3 above)
Comment (talmacschen-arch) [reply gpbackman/gpbckpconfig/utils_db.go:55]: This seems to be a misunderstanding. Just to clarify the facts:
The original code sql.Open("sqlite3", path) (without URI) defaults to mode=rwc (read + write + create) in go-sqlite3, which is why it was silently creating empty files.
The new code file:path?mode=rw explicitly sets it to read + write, but without create.
Write permissions are strictly necessary—operations like backup-delete, backup-clean, and history-clean all require UPDATE/DELETE access to the history DB.
The new code actually has narrower permissions than the original (removed create), not broader. I suggest we reply politely to clarify this and keep the code as is.

File: gpbackman/cmd/wrappers.go (hunk 4 above)
Comment (talmacschen-arch) [reply gpbackman/cmd/wrappers.go]: Thanks for raising this — I dug into the deployment model to assess the risk:

- `make install` (`Makefile:108-123`) only places `gpbackman` on the coordinator; `$COORDINATOR_DATA_DIRECTORY` (set by `greenplum_path.sh`) points unambiguously at that one cluster's history DB. The "jump host with multiple clusters' history files" scenario is non-standard.
- `backup-info` / `report-info` (read-only): wrong cluster's DB → operator immediately sees unfamiliar timestamps and stops; no destructive action.
- `backup-delete` / `backup-clean` for **local** backups: SSH to segments (`backup_delete.go:516`); the wrong cluster's hosts simply fail.
- `backup-delete --plugin-config` for **S3** backups: this is the real risk, but only if the plugin config *and* history DB are both mismatched, *and* deployment is non-standard.
- `history-clean`: writes only a local DB copy, no source-cluster impact.

**Compromise proposal**: limit the env-var fallback to **read-only commands** (`backup-info`, `report-info`); destructive commands (`backup-delete`, `backup-clean`, `history-clean`) keep the path explicit — either `--history-db` or cwd. That preserves the standard-coordinator UX win from #96 while removing the cross-cluster footgun for anything that mutates state.

If you'd prefer a stricter `--auto-load-history-db` opt-in even for read-only commands, happy to switch. WDYT?

Comment (talmacschen-arch) [reply gpbackman/cmd/wrappers.go]: Implemented  in 77e41407:

- New `--auto-load-history-db` persistent flag (default off). When off, behaviour matches upstream `main` — `getHistoryDBPath` returns `gpbackup_history.db` resolved against cwd. When on, the env-var chain (`$COORDINATOR_DATA_DIRECTORY` → `$MASTER_DATA_DIRECTORY` → cwd) kicks in.
- Destructive commands (`backup-delete`, `backup-clean`, `history-clean`) inherit the same flag, so they require either an explicit `--history-db` or a deliberate opt-in — the cross-cluster footgun is closed by default.
- Also folded in the wording fix on `wrappers.go:87` (dropped "Greenplum") and trimmed the README description per the other threads.
- The not-found error message now mentions `--auto-load-history-db` rather than implying that setting env vars alone is enough.
- Tests cover the opt-in matrix (off + env → cwd, on + env → env path, on + no env → cwd, explicit `--history-db` always wins).

The `OpenHistoryDB` safe-open change (`os.Stat` pre-check + `mode=rw` URI) from the original commits is preserved as-is. PTAL when you have a moment.

File: gpbackman/gpbckpconfig/utils_db.go [hunk 5]
```diff
@@ -21,15 +21,38 @@ package gpbckpconfig
...
+			return nil, fmt.Errorf(
+				"gpbackup history database file not found: %s. "+
+					"Specify the path via --history-db, run gpbackman from "+
+					"the directory that contains gpbackup_history.db, or "+
+					"pass --auto-load-history-db to resolve it from "+
+					"$COORDINATOR_DATA_DIRECTORY (or $MASTER_DATA_DIRECTORY)",
+				historyDBPath,
+			)
+		}
+		return nil, err
```
Comment (MisterRaindrop) [inline gpbackman/gpbckpconfig/utils_db.go]: is better `return nil, fmt.Errorf("stat history db %q: %w", historyDBPath, err)`

Comment (talmacschen-arch) [reply gpbackman/gpbckpconfig/utils_db.go]: Good catch, applied in 70097db8 — wrapped with fmt.Errorf("stat history db %q: %w", historyDBPath, err) to keep errors.Is/As working while adding path/operation     context. Thanks!

**Review by MisterRaindrop — APPROVED** [review]
LGTM

File: gpbackman/cmd/constants.go [hunk 6]
```diff
@@ -72,4 +73,12 @@ var (
 	beforeTimestamp string
 	// Timestamp to delete all backups after.
 	afterTimestamp string
+
+	// historyDBEnvVars lists, in priority order, the environment variables
+	// inspected when --history-db is not supplied. They are exported by the
+	// standard Cloudberry/Greenplum cluster environment scripts.
+	historyDBEnvVars = []string{
+		"COORDINATOR_DATA_DIRECTORY",
+		"MASTER_DATA_DIRECTORY",
```
Comment (woblerr) [inline gpbackman/cmd/constants.go]: Supporting a legacy variable doesn't make sense. The cloudberry project switched to using the `COORDINATOR_DATA_DIRECTORY` starting with version ~`1.5.4`.

I suggest using the current approach right away and not using legacy compatibility.

Similarly, it is worth removing the mention of `MASTER_DATA_DIRECTORY` in the rest of the code.

If there are reasons to maintain compatibility with `MASTER_DATA_DIRECTORY`, let's discuss it.

@MisterRaindrop @tuhaihe  What do you think?

Comment (talmacschen-arch) [reply gpbackman/cmd/constants.go]: Thanks for the context — that makes sense given Cloudberry 1.5.4+
  standardized on COORDINATOR_DATA_DIRECTORY. The cleanup touches ~9 files                                                                                              
  (code + long help strings + README/COMMANDS + tests), so I'd like to hold                                                                                             
  off on pushing it as part of this PR until the maintainers have weighed                                                                                               
  in on the overall direction. Happy to drop MASTER_DATA_DIRECTORY entirely                                                                                             
  in a follow-up commit (or a separate PR) once that's confirmed.

Comment (tuhaihe) [reply gpbackman/cmd/constants.go]: I think we can remove MASTER_DATA_DIRECTORY support.

**Comment by talmacschen-arch** [comment]
@woblerr     CI s3_plugin_e2e failed in the locale-setup step (dnf 404s                                                                                                   
  on Rocky 9.7 mirrors — see #issue-link if filed). It's unrelated to                                                                                                   
  this PR's changes; could you re-run the failed job when convenient?                                                                                                   
  Thanks!

File: gpbackman/cmd/constants.go (hunk 6 above)
Comment (MisterRaindrop) [reply gpbackman/cmd/constants.go]: > I think we can remove MASTER_DATA_DIRECTORY support.

+1,  remove MASTER_DATA_DIRECTORY support.

Comment (talmacschen-arch) [reply gpbackman/cmd/constants.go]: Done in 2d886893 — `MASTER_DATA_DIRECTORY` removed from the resolution
  chain and from all related help/docs/tests. The `cmd/constants.go`                                                                                                    
  comment is also updated to drop "Greenplum". Thanks for the consensus!

Addressed in 2d886893 — removing `(or $MASTER_DATA_DIRECTORY)` made                                                                                                   
  the line naturally shorter.  

Done in 2d886893 — `cmd/constants.go:79` now says "Cloudberry" only.

**Comment by talmacschen-arch** [comment]
@tuhaihe @woblerr — pushed 2d886893 with the MASTER_DATA_DIRECTORY                                                                                                    
  cleanup we agreed on (per @woblerr's request and @tuhaihe @MisterRaindrop's                                                                                           
  +1). The new workflow runs are sitting in `action_required` (GitHub's                                                                                                 
  external-fork CI gate). Could one of you approve them when convenient?                                                                                                
                                                                                                                                                                        
  cc @MisterRaindrop for visibility — feel free to re-review once CI clears.

**Review by woblerr — APPROVED** [review]

**Comment by woblerr** [comment]
LGTM, thank you for your efforts.

**Comment by MisterRaindrop** [comment]
LGTM
